FROM mcr.microsoft.com/playwright/python:v1.58.0-noble

RUN apt-get update && apt-get install -y --no-install-recommends \
    fonts-noto-cjk \
    locales \
    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen en_US.UTF-8 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN pip install --no-cache-dir playwright==1.58.0 requests beautifulsoup4 pyyaml \
    browser-use==0.12.2

RUN mkdir -p /home/user
WORKDIR /home/user
