ARG BASE_IMAGE=hiagent-sandbox-base
FROM ${BASE_IMAGE}

# Data science Python packages
RUN pip install --no-cache-dir \
    pandas \
    numpy \
    matplotlib \
    seaborn \
    scikit-learn \
    scipy \
    tabulate
