import { describe, expect, it, jest } from "@jest/globals";
import { renderToStaticMarkup } from "react-dom/server";

jest.mock("@/i18n", () => ({
  useTranslation: () => ({
    locale: "en",
    t: (key: string, params?: Record<string, string | number>) => {
      const dict: Record<string, string> = {
        "artifacts.recentOutputs": "Recent outputs",
        "artifacts.browseByPath": "Browse by path",
        "artifacts.previewReady": "Preview-ready outputs",
        "artifacts.otherOutputs": "Other outputs",
        "artifacts.downloadFile": "Download file",
        "artifacts.preview": "Preview",
        "artifacts.fileCount": `${params?.count ?? 0} file generated`,
        "artifacts.filesCount": `${params?.count ?? 0} files generated`,
        "library.noArtifactsHint": "Artifacts generated by agents will appear here",
        "artifacts.noFiles": "No files generated yet",
        "artifacts.pathRoot": "All files",
        "artifacts.folderEmpty": "No files in this folder yet.",
        "explorer.deleteFileLabel": `Delete ${params?.name ?? ""}`,
        "artifacts.categoryImage": "Image",
        "artifacts.categoryHtml": "HTML",
        "artifacts.categoryText": "Text",
        "artifacts.categoryCode": "Code",
        "artifacts.categoryFile": "File",
        "artifacts.categoryPdf": "PDF",
        "artifacts.size.zero": "0 B",
        "artifacts.size.b": `${params?.size ?? 0} B`,
        "artifacts.size.kb": `${params?.size ?? 0} KB`,
        "artifacts.size.mb": `${params?.size ?? 0} MB`,
        "artifacts.size.gb": `${params?.size ?? 0} GB`,
        "library.viewGrid": "Grid view",
        "library.viewList": "List view",
      };
      return dict[key] ?? key;
    },
  }),
}));

jest.mock("@/shared/hooks/use-session-filtered-artifacts", () => ({
  useSessionFilteredArtifacts: <T,>(items: readonly T[]) => items,
}));

jest.mock("@/features/agent-computer/components/ArtifactPreviewDialog", () => ({
  ArtifactPreviewDialog: () => null,
}));

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { ArtifactFilesPanel } = require("./ArtifactFilesPanel");

describe("ArtifactFilesPanel", () => {
  it("renders one newest-first artifact list without mode controls", () => {
    const html = renderToStaticMarkup(
      <ArtifactFilesPanel
        conversationId="conv-1"
        artifacts={[
          {
            id: "old",
            name: "notes.md",
            contentType: "text/markdown",
            size: 10,
            createdAt: "2026-04-16T09:00:00.000Z",
            filePath: "notes.md",
          },
          {
            id: "new",
            name: "preview.png",
            contentType: "image/png",
            size: 20,
            createdAt: "2026-04-16T10:00:00.000Z",
            filePath: "outputs/preview.png",
          },
        ]}
      />,
    );

    expect(html).not.toContain("Browse by path");
    expect(html).not.toContain("Grid view");
    expect(html).not.toContain("List view");
    expect(html).toContain("2 files generated");
    expect(html).toContain("outputs");
    expect(html).toContain("Download file");
    expect(html.indexOf("preview.png")).toBeLessThan(html.indexOf("notes.md"));
  });

  it("renders flat artifacts in the same compact list", () => {
    const html = renderToStaticMarkup(
      <ArtifactFilesPanel
        conversationId="conv-1"
        artifacts={[
          {
            id: "flat-1",
            name: "archive.zip",
            contentType: "application/zip",
            size: 10,
            createdAt: "2026-04-16T09:00:00.000Z",
          },
        ]}
      />,
    );

    expect(html).not.toContain("Browse by path");
    expect(html).toContain("1 file generated");
  });

  it("keeps preview actions for previewable artifacts", () => {
    const html = renderToStaticMarkup(
      <ArtifactFilesPanel
        conversationId="conv-1"
        artifacts={[
          {
            id: "docx-1",
            name: "palantir-ontology-report.docx",
            contentType:
              "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            size: 42,
            createdAt: "2026-04-16T10:00:00.000Z",
            filePath: "outputs/palantir-ontology-report.docx",
          },
          {
            id: "zip-1",
            name: "archive.zip",
            contentType: "application/zip",
            size: 8,
            createdAt: "2026-04-16T09:00:00.000Z",
          },
        ]}
      />,
    );

    expect(html).not.toContain("Preview-ready outputs");
    expect(html).toContain("palantir-ontology-report.docx");
    expect(html).toContain("Preview");
  });
});
