import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  AppWindow,
  Archive,
  ArrowDownToLine,
  ArrowUpFromLine,
  AtSign,
  Axe,
  BadgeHelp,
  Ban,
  BarChart3,
  Bell,
  Binary,
  BookMarked,
  BookOpen,
  Bookmark,
  Box,
  Boxes,
  Braces,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Calculator,
  Calendar,
  Camera,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  CodeXml,
  Compass,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  Download,
  Dumbbell,
  Eye,
  FileArchive,
  FileCode,
  FileJson,
  FileSearch,
  FileText,
  Film,
  Filter,
  Flame,
  FlaskConical,
  FolderSearch,
  FolderTree,
  Forward,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitFork,
  Glasses,
  Globe,
  Globe2,
  GraduationCap,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Hourglass,
  Image,
  Inbox,
  KeyRound,
  Keyboard,
  Lamp,
  Landmark,
  Laptop,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  Library,
  Lightbulb,
  LineChart,
  Link2,
  List,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageCircle,
  MessageSquare,
  Mic,
  MonitorPlay,
  Moon,
  MousePointer2,
  MousePointerClick,
  Music,
  Network,
  Newspaper,
  Package,
  PaintBucket,
  Paperclip,
  PanelBottom,
  PenTool,
  Pencil,
  Phone,
  PiggyBank,
  Pin,
  Pipette,
  Pizza,
  Plane,
  Play,
  Plug,
  PlusSquare,
  Puzzle,
  Quote,
  Radar,
  Radio,
  Receipt,
  Rocket,
  Rss,
  Save,
  Scale,
  Scan,
  ScrollText,
  Search,
  Send,
  Server,
  Settings2,
  Shapes,
  Share2,
  Shield,
  ShoppingCart,
  Sigma,
  Smartphone,
  Snowflake,
  Sparkles,
  Speaker,
  Square,
  SquareTerminal,
  Star,
  StickyNote,
  Sun,
  Swords,
  Table2,
  Tag,
  Target,
  Telescope,
  Terminal,
  Ticket,
  Timer,
  Train,
  Trash2,
  TreePine,
  Trophy,
  Truck,
  Umbrella,
  Upload,
  UserRound,
  Vault,
  Video,
  Wallet,
  Wand2,
  Watch,
  Webhook,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/** Per-tool glyph for activity UIs (progress card, computer panel). Each known tool has its own icon. */
const TOOL_ICONS: Record<string, LucideIcon> = {
  web_search: Search,
  web_fetch: Download,
  user_ask: HelpCircle,
  user_message: MessageSquare,
  message_user: MessageCircle,
  memory_store: Archive,
  memory_search: Library,
  memory_list: List,
  image_generate: Image,
  task_complete: CheckCircle2,
  code_run: Play,
  code_interpret: CodeXml,
  shell_exec: Terminal,
  shell_view: Eye,
  shell_wait: Hourglass,
  shell_write: PenTool,
  shell_kill: Ban,
  package_install: Package,
  file_read: FileText,
  file_write: Save,
  file_edit: Pencil,
  file_list: FolderTree,
  file_glob: FolderSearch,
  file_search: FileSearch,
  browser_use: Compass,
  browser_navigate: MapPin,
  browser_view: AppWindow,
  browser_click: MousePointerClick,
  browser_input: Keyboard,
  browser_select: ListChecks,
  browser_scroll_up: ChevronUp,
  browser_scroll_down: ChevronDown,
  browser_press_key: KeyRound,
  browser_console_exec: SquareTerminal,
  browser_console_view: PanelBottom,
  document_read: BookOpen,
  database_create: Database,
  database_query: Table2,
  database_schema: Sigma,
  computer_screenshot: Camera,
  computer_action: MousePointer2,
  preview_start: MonitorPlay,
  preview_stop: Square,
  plan_create: ClipboardList,
  agent_spawn: GitFork,
  agent_send: Send,
  agent_receive: Inbox,
  agent_wait: Clock,
  activate_skill: Sparkles,
  load_skill: BookMarked,
};

/**
 * Large pool of distinct glyphs — used so every unknown or MCP tool name maps to its own
 * stable icon via hash (no shared category fallback).
 */
/** Icons for skills — stable per skill id, separate from tool fallback pool. */
const SKILL_ICON_POOL: readonly LucideIcon[] = [
  Sparkles,
  BookMarked,
  Zap,
  Cpu,
  Target,
  Shield,
  FlaskConical,
  Workflow,
  Puzzle,
  Layers,
  PenTool,
  LineChart,
  Wand2,
  ScrollText,
  GraduationCap,
  Lightbulb,
  Hammer,
  Telescope,
  Network,
  GitBranch,
  Compass,
  Braces,
  Image,
];

const TOOL_ICON_POOL: readonly LucideIcon[] = [
  Wrench,
  Hammer,
  Zap,
  Cpu,
  Target,
  Shield,
  FlaskConical,
  Workflow,
  Puzzle,
  Layers,
  LineChart,
  Wand2,
  ScrollText,
  GraduationCap,
  Lightbulb,
  Telescope,
  Network,
  GitBranch,
  Braces,
  Code,
  Globe,
  Globe2,
  Plug,
  Box,
  Boxes,
  Briefcase,
  Brain,
  Bug,
  Brush,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Cloud,
  Compass,
  Cookie,
  Copy,
  CreditCard,
  Crosshair,
  Crown,
  Dumbbell,
  Eye,
  FileArchive,
  FileCode,
  FileJson,
  Film,
  Filter,
  Flame,
  Forward,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  Glasses,
  HardDrive,
  Headphones,
  Heart,
  Hexagon,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  LayoutDashboard,
  LayoutTemplate,
  Link2,
  Lock,
  Mail,
  Map,
  Medal,
  Mic,
  Moon,
  Music,
  Newspaper,
  PaintBucket,
  Paperclip,
  Phone,
  PiggyBank,
  Pin,
  Pipette,
  Pizza,
  Plane,
  PlusSquare,
  Quote,
  Radar,
  Radio,
  Receipt,
  Rocket,
  Rss,
  Scale,
  Scan,
  Server,
  Settings2,
  Shapes,
  Share2,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Speaker,
  Star,
  StickyNote,
  Sun,
  Swords,
  Tag,
  Ticket,
  Timer,
  Train,
  Trash2,
  TreePine,
  Trophy,
  Truck,
  Umbrella,
  Upload,
  UserRound,
  Vault,
  Video,
  Wallet,
  Watch,
  Webhook,
  Wheat,
  Wifi,
  Wind,
  Wine,
  AlarmClock,
  ArrowDownToLine,
  ArrowUpFromLine,
  AtSign,
  Axe,
  BadgeHelp,
  BarChart3,
  Bell,
  Binary,
  Bookmark,
];

function stableHash(input: string): number {
  let h = 0;
  for (let i = 0; i < input.length; i += 1) {
    h = (h * 31 + input.charCodeAt(i)) >>> 0;
  }
  return h;
}

function toolIconFromPool(toolName: string): LucideIcon {
  const normalized = toolName.trim().toLowerCase() || "tool";
  const idx = stableHash(`tool:${normalized}`) % TOOL_ICON_POOL.length;
  return TOOL_ICON_POOL[idx] ?? Wrench;
}

/**
 * Deterministic icon for a skill id (raw `name` from tool input), so the same skill
 * always shows the same glyph in progress and computer panels.
 */
export function getSkillIcon(skillId: string): LucideIcon {
  const key = skillId.trim().toLowerCase() || "skill";
  const idx = stableHash(key) % SKILL_ICON_POOL.length;
  return SKILL_ICON_POOL[idx] ?? Sparkles;
}

export function getToolIcon(toolName: string): LucideIcon {
  const direct = TOOL_ICONS[toolName];
  if (direct) return direct;
  return toolIconFromPool(toolName);
}

/**
 * Icon for a timeline step: tool by raw name, skill by normalized display name.
 */
export function getTimelineToolOrSkillIcon(
  kind: "tool" | "skill",
  rawToolName: string | undefined,
  skillKey: string | undefined,
  displayName: string | undefined,
): LucideIcon {
  if (kind === "skill") {
    const fromKey = skillKey?.trim();
    if (fromKey) return getSkillIcon(fromKey);
    const id =
      displayName?.trim()
        ? displayName.trim().toLowerCase().replace(/\s+/g, "-")
        : "skill";
    return getSkillIcon(id);
  }
  if (rawToolName) return getToolIcon(rawToolName);
  return Wrench;
}
